In [1]:
import pandas as pd

In [4]:
file = '20160301_TE_survey_cleaned.csv'

In [5]:
df = pd.read_csv(file)

In [6]:
df.head()

,ID,T(K),Z*10^-4 reported,Resist(Ohm.cm),Seebeck(uV/K),kappaZT,Unnamed: 6,Resist(400K),Seebeck(400K),Pf(W/K^2/m),...,total_atoms_per_unit_cell,average_atomic_volume,ICSD_of_structure,temp of ICSD (K),S^2,ke/ktotal,space_group,number_symmetry_elements,Unnamed: 34,Unnamed: 35
0,1.0,300.0,NaN,50.000000,-462.967,0.000129,1.0,50.000000,-462.967,4.286770e-07,...,20.0,10.3485,35218,300.0,214338.44310,NaN,62.0,8.0,NaN,NaN
1,2.0,400.0,NaN,50.000000,-462.967,0.000171,1.0,50.000000,-462.967,4.286770e-07,...,20.0,10.3485,35218,300.0,214338.44310,NaN,62.0,8.0,NaN,NaN
2,3.0,700.0,NaN,2.417492,-470.651,0.006414,1.0,50.000000,-462.967,9.162900e-06,...,20.0,10.3485,35218,300.0,221512.36380,NaN,62.0,8.0,NaN,NaN
3,4.0,1000.0,NaN,0.177490,-279.829,0.044118,1.0,50.000000,-462.967,4.411760e-05,...,20.0,10.3485,35218,300.0,78304.26924,NaN,62.0,8.0,NaN,NaN
4,5.0,300.0,NaN,0.046115,-201.708,0.026468,1.0,0.046115,-201.708,8.822830e-05,...,20.0,10.3870,82210,300.0,40686.11726,NaN,62.0,8.0,NaN,NaN