# Tutorial for `temann` module

---

## 1. Installing
1. `git clone https://github.com/Luochenghuang/TEMANN`
    - if already cloned, use `git pull` to download the latest version
2. `cd TEMANN`

3. `python setup.py install`

---

## 2. Importing `temann`

In [1]:
import temann

---

## 3. Accessing the data used to train the model 
- TEMDB: ThermoElectric Materials DataBase
- from DOI: http://dx.doi.org/10.1021/cm400893e

In [2]:
from temann.data import TEMDB

#### `TEMDB` is a `pandas.DataFrame` instance and has the same functionality

In [3]:
TEMDB.head()

,ID,T(K),Z*10^-4 reported,Resist(Ohm.cm),Seebeck(uV/K),kappaZT,Unnamed: 6,Resist(400K),Seebeck(400K),Pf(W/K^2/m),...,total_atoms_per_unit_cell,average_atomic_volume,ICSD_of_structure,temp of ICSD (K),S^2,ke/ktotal,space_group,number_symmetry_elements,Unnamed: 34,Unnamed: 35
0,1.0,300.0,NaN,50.000000,-462.967,0.000129,1.0,50.000000,-462.967,4.286770e-07,...,20.0,10.3485,35218,300.0,214338.44310,NaN,62.0,8.0,NaN,NaN
1,2.0,400.0,NaN,50.000000,-462.967,0.000171,1.0,50.000000,-462.967,4.286770e-07,...,20.0,10.3485,35218,300.0,214338.44310,NaN,62.0,8.0,NaN,NaN
2,3.0,700.0,NaN,2.417492,-470.651,0.006414,1.0,50.000000,-462.967,9.162900e-06,...,20.0,10.3485,35218,300.0,221512.36380,NaN,62.0,8.0,NaN,NaN
3,4.0,1000.0,NaN,0.177490,-279.829,0.044118,1.0,50.000000,-462.967,4.411760e-05,...,20.0,10.3485,35218,300.0,78304.26924,NaN,62.0,8.0,NaN,NaN
4,5.0,300.0,NaN,0.046115,-201.708,0.026468,1.0,0.046115,-201.708,8.822830e-05,...,20.0,10.3870,82210,300.0,40686.11726,NaN,62.0,8.0,NaN,NaN

In [13]:
TEMDB.describe()

,ID,T(K),Z*10^-4 reported,Resist(Ohm.cm),Seebeck(uV/K),kappaZT,Unnamed: 6,Resist(400K),Seebeck(400K),Pf(W/K^2/m),...,atoms_per_formula_unit,total_atoms_per_unit_cell,average_atomic_volume,temp of ICSD (K),S^2,ke/ktotal,space_group,number_symmetry_elements,Unnamed: 34,Unnamed: 35
count,1098.000000,1087.000000,63.000000,1098.000000,1098.000000,1.087000e+03,1093.000000,352.000000,352.000000,1.098000e+03,...,1094.000000,1094.000000,1094.000000,1094.000000,1.097000e+03,7.080000e+02,1081.000000,1081.000000,0.0,0.0
mean,549.500000,576.356946,127.571288,22.695998,-40.155270,4.116614e-01,4.784995,23.726651,-50.673684,6.985113e-04,...,8.304122,25.925612,16.470370,297.957038,3.874359e+04,9.137419e-01,148.825162,50.690102,NaN,NaN
std,317.109603,264.474832,295.524366,449.261071,192.691410,7.039567e-01,3.065893,119.162678,178.745718,1.059576e-03,...,10.805796,24.807019,6.922686,45.711004,7.465191e+04,7.393718e+00,77.482459,62.470980,NaN,NaN
min,1.000000,300.000000,0.100000,0.000065,-752.196000,5.296550e-08,1.000000,-247.307000,-600.164000,1.765520e-10,...,1.000000,4.000000,9.116250,15.000000,1.000000e-02,6.447350e-08,2.000000,2.000000,NaN,NaN
25%,275.250000,300.000000,0.417075,0.001512,-163.359500,2.874886e-02,2.000000,0.001702,-123.586000,6.108548e-05,...,3.000000,12.000000,10.922917,298.000000,5.622615e+03,4.759174e-02,62.000000,8.000000,NaN,NaN
50%,549.500000,400.000000,0.730808,0.004872,-67.600000,1.231760e-01,4.000000,0.005499,-56.592800,2.152560e-04,...,5.000000,20.000000,12.943875,300.000000,1.823958e+04,1.531699e-01,186.000000,16.000000,NaN,NaN
75%,823.750000,700.000000,1.391570,0.022964,99.358325,4.641355e-01,7.000000,0.040973,91.581000,8.472895e-04,...,7.000000,32.000000,21.541667,300.000000,4.452100e+04,4.120509e-01,220.000000,48.000000,NaN,NaN
max,1098.000000,1000.000000,1000.000000,14500.000000,1235.430000,6.666667e+00,11.000000,809.808399,321.429000,6.728000e-03,...,58.000000,208.000000,36.937159,1198.000000,1.526287e+06,1.265311e+02,227.000000,192.000000,NaN,NaN

---

## 4. Accessing submodules

In [4]:
from temann import interpret, querry, spacegroup, util

#### `interpret` submodule

In [11]:
interpret.get_empirical_formula("Ca0.98La0.02MnO3")

{'Ca': 0.98, 'La': 0.02, 'Mn': 1, 'O': 3}

#### `spacegroup` submodule

In [12]:
spacegroup.expand_spacegroup(30)

spacegroup                       30
crystal system         orthorhombic
lattice type                      P
centrosymmetric               False
symmetry operations               4
Name: 29, dtype: object

---

## 5. To be continued...